spring:
    application:
        name: "WECHAT"
    port: 8080
    jpa.hibernate.ddl-auto: update
    datasource:
        url: "jdbc:mysql://localhost:3306/test"
        username: "hewenhan"
        password: "033481033481"
    main:
        allow-bean-definition-overriding: true

logging:
    level:
        org.springframework.web: INFO
        com.yd.spring.wechatCenter: DEBUG


mysql:
    host: "localhost"
    port: 3306
    db: "test"
    userName: "hewenhan"
    password: "033481033481"
    maxPool: 20

redis:
    host: "localhost"
    password: "033481033481"
    port: 6379
    db: 0

eureka:
    instance:
        statusPageUrlPath: "${management.endpoints.web.base-path}/info"
        healthCheckUrlPath: "${management.endpoints.web.base-path}/health"
    client:
        serviceUrl:
            defaultZone: "http://localhost:8761/eureka/"
        enabled: false

management:
    endpoint:
        health.show-details: always
    endpoints:
        web:
            exposure.include: "*"
            base-path: "/serviceInfo"
